timeout=5
default=0
remember_last=1
quiet=0
editor=1
resolution=native
show_names=1
center_info=1
entries_per_page=3
mouse=1
font=jetbrains
theme=glassmorphism
log=1

entry {
    name    = "Arch Linux"
    icon    = \EFI\visor\icons\arch.png
    initrd  = \intel-ucode.img
    kernel  = \vmlinuz-linux
    initrd  = \initramfs-linux.img
    cmdline = "root=PARTUUID=66903304-9102-4d2b-ba5a-31a286a7b2e0 rw rootflags=subvol=@ quiet"
}
